### ISSUE TITLE
Cleanup after rabbitmanager tests

### ISSUE THREAD

**Issue by Hexcles** [taskcluster/taskcluster-pulse#22]
Ideally, tests cases (or at least, test suites) should be torn down properly even when some tests fail. In our context, if the rabbitmq tests that touch the management database (e.g. users, permissions) fail, there are chances that some test data will be left over and cause subsequent tests to fail.

Yet I'm not able to find a proper way to do this using HTTP management APIs: importing (POST) "definitions" (i.e. management DB) will merge the uploaded with the existing ones; and there is no counterpart of the command-line `rabbitmqctl reset` (which is reasonable, as it would reset the root account as well).

At this point, however, I feel like it is more reasonable to rely on CI to do this. I believe Travis will grab a new, clean instance every time. Is that right? What about the planned dogfood, Taskcluster-based CI, that we briefly mentioned?

As for local development/testing, eventually we'll have a container and can write some setup scripts. Besides, it is not a good idea to reset the local rabbitmq automatically.

**Comment by djmitche** [comment]
From a skim of http://hg.rabbitmq.com/rabbitmq-management/raw-file/rabbitmq_v3_3_4/priv/www/api/index.html it looks like you could enumerate users with `GET /api/users` and then `DELETE /api/users/<name>` for each one.  Or, if you know the names of the users that the tests created (maybe just keep a list?) you could just try to delete those and ignore errors.

Similarly, with permissions, you can list them all and then delete them.

Ideally this happens after each test *case*, so that you're not left wondering if the failure of test N left dirty state for test N+1, or if the failure of N+1 is also significant.  Relying on CI and containerized testing is not a great solution, as it's *much* more difficult for newcomers to get working.

**Comment by Hexcles** [comment]
A bit more context about my original confusion: it is like a recursion of testing. There are APIs for listing users and deleting users, etc., and we have actually implemented them in this wrapper library. It is possible to use these methods in the teardown to clean up, but these methods are also the subjects we are testing. If they are correctly implemented, then most (*) tests would not fail as those tests are just simple invocations of these methods, and no cleanup is needed; otherwise, when tests do fail and we need to clean up, there is a high chance that these methods have bugs and the cleanup based on them might not be reliable any more.

(*) There are indeed a few more complicated tests that could be improved to better handle failures though, which I will do later.

**Comment by djmitche** [comment]
I was suggesting using the RabbitMQ API directly (making HTTP requests directly) from the test setup/teardown methods.

**Comment by Hexcles** [comment]
Closing this issue (by #32 / c1a116fa0e0204b9e2d7f89977b510fab13d321b).

The ideal solution should be replacing the method calls of `deleteUser` and `deleteQueue` (in `rabbit_test.js`) with direct HTTP requests to avoid circularity (i.e. relying on the testee in teardown). I've added a TODO in the [code](https://github.com/taskcluster/taskcluster-pulse/blob/63b8269674ea5ad5e8a84a1100ebefce0dd8fdfd/test/rabbit_test.js#L26) for that.
